### ISSUE TITLE
Allow generation of homeassistant addresses 

### ISSUE THREAD

**Issue by cpauls** [cpauls/knx-ga-generator#3]
Hallo,
ich nutze Homeassistant zusammen mit KNX. 
Der Generator könnte auch Adressen für Homeassistant erzeugen. Die Konfiguration wird dann etwas komplizierter - geht aber gerade noch. 

Könnte jemand mit diesem Feature umgehen? 
 
Konfiguration:
```yaml
actionGroupConfig:
  - name: "Licht"
    main: 10
    usedForFeatures: [ "schalten", "dimmen" ] #usedForFeatures
    actions: [
      { name: "schalten", middle: 1, ha: ["light.address"] }, #implement later
      { name: "status",  middle: 3, ha: ["light.state_address"]}
     ]
building:
  name: "castle"
  floors:
    - floor: "EG"
      rooms:
        - room: "Wohnzimmer"
          things: [
            { feature: "schalten", description: "Steckdose rechts", sub: 4 },
```

erzeugt: 
```yaml
light:
  - name: 'EG Wohnzimmer Steckdose rechts'
    address: '10/1/4'
    state_address: '10/3/4'
```
